### ISSUE TITLE
vampnet its wierd dip

### ISSUE THREAD

**Issue by euhruska** [markovmodel/deeptime#21]
in vampnet/examples/Alanine_dipeptide.ipynb
the its
```
its = vamp.get_its(pred_ord, lag)
vamp.plot_its(its, lag)
```
gives a wierd dip of the third timescale around lagtime=80. What is causing it?
![download](https://user-images.githubusercontent.com/9983894/44889170-7143a600-ac9a-11e8-90d8-6f532f5e3227.png)

**Comment by amardt** [comment]
At tau 80, you are already in the regime where the tau lag is larger than the timescale (grey area). So this area is not important for checking for converged timescales. So you don't have to worry about it here.

However, we made the observation for a non reversible toy model, that these dips also occur in the important regime. There it happens when the tau equals some periodic behavior of the system. 

Best
Andreas
