### ISSUE TITLE
Estimating Koopman Operator with data from multiple trajectories

### ISSUE THREAD

**Issue by niklastoe** [markovmodel/deeptime#23]
Hi,

in [the Alanine dipeptide example with multiple files ](https://github.com/markovmodel/deeptime/blob/master/vampnet/examples/Alanine_dipeptide_multiple_files.ipynb), `pred_ord` is calculated for `total_data_source`, i.e. for all trajectories. `pred_ord` is passed on to `vamp.get_its` and `vamp.get_ck_test`, both of which call `vamp.estimate_koopman_op`. `pred_ord` does not contain any information about the trajectories so `vamp.estimate_koopman_op` will consider pairs across trajectories when calculating `c_tau` e.g. `traj1[-1]` with `traj2[tau-1]`. These pairs are random since there's no connection between the trajectories.

In the example it's not a big issue since tau is much smaller than the length of each individual trajectory. Unless the random pairs correspond to transitions that are extremely rare, the Koopman operator won't differ much. 

If that's the case though, what should one do? Estimate the Koopman operator for each individual trajectory and average all of them? I did that for the example, the transition probabilities involving the sparsely populated state 3 change a little bit. 

![image](https://user-images.githubusercontent.com/21060346/46868621-3b611800-ce29-11e8-9ac4-0dda83a6e502.png) 
![image](https://user-images.githubusercontent.com/21060346/46868624-40be6280-ce29-11e8-9e6c-eaec5889321f.png)

Out of curiosity, is there any explanation for the negative values in the matrix or is that a numerical issue?

In other scenarios where tau might be in the range of 10^1 ns and trajectory lengths are in the range of 10^2 ns there would be a considerable number of random pairs and a large deviation in the Koopman operator. 

Please let me know what you think. I assume I'll be working with trajectories that are 5-10 tau long so I'd like a convenience function that takes care of this. If you agree with the overall thought and think that averaging over all the Koopman operators from different trajectories is fine, I'll go ahead and write it.

Niklas

**Comment by amardt** [comment]
Hi,
you are right, this is an issue. And averaging over it is definitely not the right solution. Instead you should just not include the datapoints crossing the trajectories into your estimation. 
We will adapt our function for this case as soon as possible. 
 
The negative value issue:
The Koopman operator can have negative values. You cannot interpret it as a probability transition matrix as for a real Markov State Model. The row sum is still 1 though. But usually this is not really an issue. You can still interpret the output of your network as a fuzzy clustering and use the eigenvalues of the Koopman matrix for calculating the implied timescales. 
For non-reversible and non-stationary systems the last point breaks down though, because the eigenvalues will become complex. But the Koopman model still holds and is able to describe the dynamical system (via the singular values/functions).

If you want to have a valid transition matrix, have a look at our paper:
[Deep Generative Markov State Models](https://arxiv.org/abs/1805.07601)
This solves this issue and also shows you how you can construct a generative model which approximates the conditional probability distribution in configuration space. By this you can simulate a new trajectory with unseen configurations based on the conditional distribution your model learned.

Hope this helps! Otherwise just contact us!

Best
Andreas

**Comment by amardt** [comment]
Hey,
we now added the multiple trajectories option for the Koopman matrix estimation. It needs them as a list though. See our Alanine-Dipeptide example with multiple files. 

If you need clarification, just ask!

Best
Andreas

**Comment by niklastoe** [comment]
Right, that's better!
